# JVM
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+UseParallelGC
# Android
android.useAndroidX=true
android.enableJetifier=false
# Performance
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
# R optimizations
android.nonTransitiveRClass=true
android.nonFinalResIds=true
kotlin.compiler.execution.strategy=in-process
