// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8VllGXiB2Bu5Lz-uYaHLhNq4ktcvJI7s',
    appId: '1:632896579678:web:a80d6c11fbcde15d8caccf',
    messagingSenderId: '632896579678',
    projectId: 'chat-team-app',
    authDomain: 'chat-team-app.firebaseapp.com',
    storageBucket: 'chat-team-app.firebasestorage.app',
    measurementId: 'G-EZZMDH8YVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoLYv54Ms6yl9ULe66Lk0HMF-ycBLDHfA',
    appId: '1:632896579678:android:64e41bd06ded3e8d8caccf',
    messagingSenderId: '632896579678',
    projectId: 'chat-team-app',
    storageBucket: 'chat-team-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUc8w4bXSwLjk0Q9hIFQLer6AQncdubfc',
    appId: '1:632896579678:ios:d548e2451dc32eaf8caccf',
    messagingSenderId: '632896579678',
    projectId: 'chat-team-app',
    storageBucket: 'chat-team-app.firebasestorage.app',
    androidClientId: '632896579678-f0i3q5f194mc23vqjb9fjiue8jtegknp.apps.googleusercontent.com',
    iosClientId: '632896579678-3p3o28l6ei4cmlavnl2o6e5f1ossbtla.apps.googleusercontent.com',
    iosBundleId: 'com.teamnana.app',
  );
}
